name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cache lib and node_modules
        uses: actions/cache@v3
        with:
          path: |
            lib
            node_modules
          key: ${{ runner.os }}-ipos-lib-${{ github.sha }}

  test:
    needs: [ build ]
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache lib and node_modules
        uses: actions/cache@v3
        with:
          path: |
            lib
            node_modules
          key: ${{ runner.os }}-ipos-lib-${{ github.sha }}

      - name: Run Tests
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
